version: '2'
services:
  proxy:
    build: .
    command: /app/bin/asynchttpproxy
    environment:
      PROXY_LOG_LEVEL: debug
      PROXY_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
